language: c

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitPPCupdate.pl
  - wget https://github.com/GRRLIB/GRRLIB/archive/4.3.2.tar.gz
  - tar -xzvf 4.3.2.tar.gz

install:
  - sudo perl devkitPPCupdate.pl
  - echo ${DEVKITPRO}
  - echo ${DEVKITPPC}
  - cd GRRLIB-4.3.2/GRRLIB && make
  - echo ${DEVKITPRO}
  - echo ${DEVKITPPC}
  - sudo make install

script:
  - make