language: c

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

before_install:
  - mkdir "${DEVKITPRO}" && mkdir "${DEVKITPRO}/libogc"
  - wget http://download.sourceforge.net/devkitpro/devkitPPC_r27-x86_64-linux.tar.bz2 -O devkitPPC-linux.tar.bz2
  - wget http://download.sourceforge.net/devkitpro/libogc-1.8.12.tar.bz2 -O libogc.tar.bz2
  - wget http://download.sourceforge.net/devkitpro/libfat-ogc-1.0.14.tar.bz2 -O libfat-ogc.tar.bz2
  - wget https://github.com/GRRLIB/GRRLIB/archive/4.3.2.tar.gz -O GRRLIB.tar.gz

install:
  - tar -xjf devkitPPC-linux.tar.bz2 -C ${DEVKITPRO}/
  - tar -xjf libogc.tar.bz2 -C ${DEVKITPRO}/libogc
  - tar -xjf libfat-ogc.tar.bz2 -C ${DEVKITPRO}/libogc
  - tar -xzvf GRRLIB.tar.gz
  - cd GRRLIB-4.3.2/GRRLIB && sudo -E make all install && cd ../..

script:
  - cd GRRMOD && make && cd ..