language: c
dist: bionic
sudo: required

os:
  - linux

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC
    - GRRLIBVERS=4.4.0

cache:
  directories:
    - ${DEVKITPRO}
    - GRRLIB-${GRRLIBVERS}/GRRLIB

before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - wget https://github.com/GRRLIB/GRRLIB/archive/v${GRRLIBVERS}.tar.gz -O GRRLIB.tar.gz

install:
  - sudo dpkg --install devkitpro-pacman.deb
  - sudo dkp-pacman --sync --sysupgrade --refresh --needed --noconfirm wii-dev libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo
  - tar -xzvf GRRLIB.tar.gz
  - (cd GRRLIB-${GRRLIBVERS}/GRRLIB && sudo -E make all install)

script:
  - (cd GRRMOD && make && sudo -E make install)
  - (cd demo && make)
