language: c

os:
  - linux

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitPPCupdate.pl
  - export DEVKITPRO=$HOME/travis/devkitPro
  - export DEVKITPPC=${DEVKITPRO}/devkitPPC

install:
  - wget https://github.com/GRRLIB/GRRLIB/archive/4.3.2.tar.gz
  - tar -xzvf 4.3.2.tar.gz
  - cd GRRLIB-4.3.2/GRRLIB && make && sudo make install
  - sudo perl devkitPPCupdate.pl

script:
  - make