language: c
sudo: false

os:
  - linux

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC
    - GRRLIBVERS=4.3.2

cache:
  directories:
    - GRRLIB-${GRRLIBVERS}/GRRLIB

before_install:
  - mkdir -p "${DEVKITPRO}/libogc"
  - wget http://download.sourceforge.net/devkitpro/devkitPPC_r29-1-x86_64-linux.tar.bz2 -O devkitPPC-linux.tar.bz2
  - wget http://download.sourceforge.net/devkitpro/libogc-1.8.17.tar.bz2 -O libogc.tar.bz2
  - wget http://download.sourceforge.net/devkitpro/libfat-ogc-1.1.2.tar.bz2 -O libfat-ogc.tar.bz2
  - wget https://github.com/GRRLIB/GRRLIB/archive/${GRRLIBVERS}.tar.gz -O GRRLIB.tar.gz

install:
  - tar -xjf devkitPPC-linux.tar.bz2 -C ${DEVKITPRO}/
  - tar -xjf libogc.tar.bz2 -C ${DEVKITPRO}/libogc
  - tar -xjf libfat-ogc.tar.bz2 -C ${DEVKITPRO}/libogc
  - tar -xzvf GRRLIB.tar.gz
  - (cd GRRLIB-${GRRLIBVERS}/GRRLIB && make all install)

script:
  - (cd GRRMOD && make && make install)
  - (cd demo && make)
