language: c
sudo: false

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

before_install:
  - mkdir -p "${DEVKITPRO}/libogc"
  - wget http://download.sourceforge.net/devkitpro/devkitPPC_r29-1-x86_64-linux.tar.bz2 -O devkitPPC-linux.tar.bz2
  - wget http://download.sourceforge.net/devkitpro/libogc-1.8.16.tar.bz2 -O libogc.tar.bz2
  - wget http://download.sourceforge.net/devkitpro/libfat-ogc-1.1.0.tar.bz2 -O libfat-ogc.tar.bz2
  - wget https://github.com/GRRLIB/GRRLIB/archive/4.3.2.tar.gz -O GRRLIB.tar.gz

install:
  - tar -xjf devkitPPC-linux.tar.bz2 -C ${DEVKITPRO}/
  - tar -xjf libogc.tar.bz2 -C ${DEVKITPRO}/libogc
  - tar -xjf libfat-ogc.tar.bz2 -C ${DEVKITPRO}/libogc
  - tar -xzvf GRRLIB.tar.gz
  - (cd GRRLIB-4.3.2/GRRLIB && make DEVKITPRO=${DEVKITPRO} DEVKITPPC=${DEVKITPPC} all install)

script:
  - (cd GRRMOD && make && make install)